name: OpenAI Agent Check
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true
          pip install pytest

      - name: Verify syntax
        run: python -m compileall .

      - name: Run tests
        run: pytest -q
